version: "3.0"

services:
  nginx: 
    image: nginx:1.21-alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - .project/src/main/webapp:/usr/share/nginx/html/
    ports:
    - 80:80
    networks:
    - frontend



  db:
    image: mysql:5.7
    environment:
     MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - wdata:/var/lib/mysql
    networks:
      - backend
    


  lavagna:
    build: ./ 
    networks:
      - backend
      - frontend

  stampo:
    build:
      context: .
      dockerfile: ./Dockerfile.stampo
    ports:
     - 8081:45001
   # networks:
  #  - frontend

    
    

volumes:
  wdata:       
networks:
  backend:
  frontend:
  



